#!/bin/bash

# Start the vision server

DIR=/home/odroid/VisionServer/server
SCRIPT=visionserver2018.py
ARGS="--calib ../data/calibration/c930e_calib.json --test"
LOG_FILE="visionserver.log"

setup_camera() {
    # set camera to fixed focus
    # can't be done in cscore
    # TODO get the right parameters!!!
    #uvdynctl -d "$1" -s 'Focus (Auto)' 0
    #uvdynctl -d "$1" -s 'Focus (Auto)' 0    
}

case "$1" in
    stop)
	pkill -f $SCRIPT
	;;

    start)
        cd $DIR
        setup_camera /dev/video0
        [ -c /dev/video1 ] setup_camera /dev/video1
        
        python3 ./$SCRIPT $ARGS >> $LOG_FILE 2>&1 < /dev/null &
	;;

    restart)
	$0 stop
	$0 start
	;;

    *)
	echo "$0 (start|stop|restart)"
	;;
esac
